spring:
  datasource:
    url: jdbc:postgresql://db:5432/devis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-batch.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/devis
          jwk-set-uri: http://keycloak:8080/realms/devis/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG

generation:
  batch-delay: 120000

keycloak:
  realm: devis
  auth-server-url: http://keycloak:8080
  resource: devis-frontend
  public-client: true
  principal-attribute: preferred_username
  credentials:
    secret: 56y6rr2sBfPqOka2yT9upf4FqNR9LvXG