spring:
  datasource:
    url: jdbc:postgresql://db:5432/devis
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-batch.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.amqp: DEBUG
    ma.agilisys.devis: DEBUG

generation:
  batch-delay: ${GENERATION_BATCH_DELAY}

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  resource: ${KEYCLOAK_CLIENT_ID}
  public-client: true
  principal-attribute: preferred_username
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

resilience4j:
  circuitbreaker:
    instances:
      documentGeneration:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      documentGeneration:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.amqp.AmqpException
          - java.net.ConnectException
          - java.net.SocketTimeoutException